#\uC350
50000 = team-dread|dy-team-dread
#\uC351
50001 = zinc|dy-zinc-icon
#\uC352
50002 = malachite|dy-malachite-icon
#\uC353
50003 = flux-collector|dy-flux-collector-icon
#\uC354
50004 = flux|dy-flux-icon
#\uC355
50005 = part-basic|dy-part-basic-icon
#\uC356
50006 = grafter|dy-grafter-icon
#\uC357
50007 = flux-outlet|dy-flux-outlet-icon
#\uC358
50008 = pipe|dy-pipe-icon
#\uC359
50009 = clockwork-drill|dy-clockwork-drill-icon
#\uC35A
50010 = accelerator|dy-accelerator-icon
#\uC35B
50011 = withdraw|dy-withdraw-icon
#\uC35C
50012 = malachite-wall|dy-malachite-wall-icon
#\uC35D
50013 = split-fabricator|dy-split-fabricator-icon
#\uC35E
50014 = core-surface|dy-core-surface-icon